### ISSUE TITLE
toString uses Guava Objects.toStringHelper() which is deprecated

### ISSUE THREAD

**Issue by michaelliudl** [seanlandsman/guavagenerators#4]
MoreObjects.toStringHelper() is replacement

**Comment by swojtasiak** [comment]
Here is a fixed version with downloadable jar.

https://github.com/swojtasiak/guavagenerators/tree/guava-18-support

**Comment by willmenn** [comment]
@seanlandsman  Could you review my pull-request and se if it's fit into your project.

**Comment by seanlandsman** [comment]
Done! Thanks for the change
